deluser --remove-home atr
deluser --remove-home axe
deluser --remove-home cag
deluser --remove-home ceh
deluser --remove-home cgs
deluser --remove-home datapal
deluser --remove-home devqa
deluser --remove-home dmc
deluser --remove-home dot2dot
deluser --remove-home ekb
deluser --remove-home hms
deluser --remove-home igb
deluser --remove-home jds
deluser --remove-home jks
deluser --remove-home jlk
deluser --remove-home jmh
deluser --remove-home jws
deluser --remove-home jxk
deluser --remove-home kmg
deluser --remove-home lab
deluser --remove-home mab
deluser --remove-home mdw
deluser --remove-home mjl
deluser --remove-home mxg
deluser --remove-home pab
deluser --remove-home par
deluser --remove-home qauser
deluser --remove-home rcg
deluser --remove-home rgc
deluser --remove-home rhd
deluser --remove-home skg
deluser --remove-home txt
deluser --remove-home jah
deluser --remove-home pxa
deluser --remove-home jsr
deluser --remove-home bdh
deluser --remove-home njg
deluser --remove-home bhn
deluser --remove-home cgt
deluser --remove-home cth
deluser --remove-home dbs
deluser --remove-home slk
deluser --remove-home mxl
deluser --remove-home bvm
deluser --remove-home cxh
deluser --remove-home jrp
deluser --remove-home pas
deluser --remove-home rxj

apt-get autoremove -y  git sudo tmux tree krb5-kdc
